### ISSUE TITLE
Ajouter le logo de Tout Naturel Haïti-Caraïbes  

### ISSUE THREAD

**Issue by alberto56** [maisonverte/maisonverte#1]

**Comment by alberto56** [comment]
Messerne, tu n'as pas inclus le logo dans ton email. SVP le mettre ici.

**Comment by alberto56** [comment]
Voir le logo en pj

![LOGO TNT](https://user-images.githubusercontent.com/808265/102903668-a6adc800-443e-11eb-9d5b-d13ca9427be8.png)

**Comment by samelohaiti** [comment]
Tout Naturel Haïti-Caraïbes

**Comment by alberto56** [comment]
@samelohaiti je vais rouvrir, car cette tâche n'est pas encore complétée; on pourra fermer quand le logo sera sur le site!
