### ISSUE TITLE
rubriques visibles et détachées l’une de l’autre

### ISSUE THREAD

**Issue by alberto56** [maisonverte/maisonverte#11]
j’aimerais que tu arranges les rubriques afin qu’elles soient
visibles et détachées l’une de l’autre.

**Comment by alberto56** [comment]
@samelohaiti svp préciser à quel endroit du site il s'agit (avec exemples)

**Comment by samelohaiti** [comment]
En haut du site web, sur la même ligne où se trouve le logo. Est-ce que les
rubriques (*Destinations, actualités, nos actions*) ne peuvent être placées
sur la même ligne que les autres. Je pense qu’à la place du numéro de
téléphone (10(256)-928 256), on pourrait placer ces rubriques en question.

Ensuite, je remarque qu’une erreur s’est glissée : Dans toutes les fiches
que tu ajoutes sur le site web, il manque la partie « *Description* ».
C’est-à-dire, chaque site naturel est présenté de cette façon :
Description, sa biodiversité, ses potentialités écotouristiques, Ses
menaces.
J’aimerais enlever ce titre dans les fiches : « Ses menaces par rapport aux
changements climatiques et les mesures à prendre pour s’adapter aux aléas
naturels ».



Voilà


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 8 mars 2021 à 13:38, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
> Ses menaces par rapport aux changements climatiques

cela sera fait dans #13 

> ne peuvent être placées sur la même ligne que les autres.

Il y en a trop pour mettre sur la même ligne. Toutefois on peut tout enlever et mettre dans un "hamburger menu" comme dans la capture d'écran ci-jointe.

<img width="1085" alt="Screen Shot 2021-03-08 at 4 35 57 PM" src="https://user-images.githubusercontent.com/808265/110385023-6a950700-802c-11eb-8857-c49e7e863ca7.png">


Qu'en penses-tu?

**Comment by samelohaiti** [comment]
La partie description n'est toujours pas visible dans la fiche de Lac
Azuei. Tous les sites naturels ici présentés ont un texte de Description.
Pour la présentation en capture d'écran, je pense que c'est bon. Sinon, on
enlève les rubriques: Notre équipe et Contact puis on met nostre e-mail en
bas de page du site web

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 8 mars 2021 à 16:36, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
OK j'y vais pour le "hamburger menu".

> partie description n'est toujours pas visible dans la fiche de Lac Azuei. Tous les sites naturels ici présentés ont un texte de Description

Pour ceci j'ai ouvert une autre tâche au #20 car ce n'est pas relié aux rubriques du haut de page.

**Comment by samelohaiti** [comment]
Dans cette capture, peux-tu placer les rubriques de cette maniere ordonnée? 

Actualités -  Personnalités du Mois – Destinations - Qui sommes-nous -  Contact

Tu peux enlever ce numéro téléphone ( 10(256)-928 256) place en haut et a droite de la barre des rubriques du site
![Capture des Rubriques](https://user-images.githubusercontent.com/75354553/110683504-1879f000-81aa-11eb-9ac2-6bcd44516ac1.png)
.

**Comment by alberto56** [comment]
L'ordre des rubriques se fait avec le champ ordre. Toutes les rubriques sont maintenant dans le menu de côté.

<img width="835" alt="Screen Shot 2021-03-15 at 8 55 38 PM" src="https://user-images.githubusercontent.com/808265/111248897-351a8b80-85e1-11eb-872c-ac08c384ed91.png">
