### ISSUE TITLE
Ses menaces par rapport aux changements climatiques et les mesures à prendre pour s’adapter aux aléas naturels

### ISSUE THREAD

**Issue by alberto56** [maisonverte/maisonverte#13]
Sinon, tu peux me donner l’accès pour que
je puisse modifier certaines fonctionnalités, notamment la partie : *Ses
menaces par rapport aux changements climatiques et les mesures à prendre
pour s’adapter aux aléas naturels *dans les fiches.J’aimerais enlever
cette partie car ces fiches constituent une offre écotouristique. Donc, on
n’a pas besoin de mettre les informations non essentielles. Peux-tu me
donner ton avis là-dessus ?

**Comment by alberto56** [comment]
@samelohaiti puisqu'il y a déjà de l'information dans ces rubriques, veux-tu les enlever des fiches elles-mêmes mais laisser le champ avec l'information dans la partie administrative? Comme ça le public ne pourra pas le voir mais l'information sera là pour d'autres usages.

**Comment by samelohaiti** [comment]
Oui, on fait comme ça.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 8 mars 2021 à 14:01, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
OK! Voir https://www.toutnaturelcaraibes.org/haiti/lac-azuei/
