### ISSUE TITLE
Sur les fiches, les photos devraient défiler, et non apparaître en bas de page

### ISSUE THREAD

**Issue by alberto56** [maisonverte/maisonverte#16]
Pour chaque
fiche, j’aimerais ajouter deux photos mais il me semble que c’est une seule
qui est visible sur le site.

**Comment by alberto56** [comment]
Les autres photos apparaissent la page de la fiche, en-bas du texte, par exemple https://www.toutnaturelcaraibes.org/haiti/etang-miragoane/

**Comment by samelohaiti** [comment]
C’est-à-dire, j’aimerais que les deux photos se défilent l’une après l’autre pour chaque site naturel présenté car j’ajoute deux photos pour chaque site naturel

**Comment by alberto56** [comment]
OK je vais changer le titre de la tâche. On mettra ça en priorité B.
