### ISSUE TITLE
Ajouter des rubriques

### ISSUE THREAD

**Issue by alberto56** [maisonverte/maisonverte#2]
Qui sommes-nous

-          Nos actions

-          Actualités

-           personnalité de la semaine

-           Evénements

-           Organisations environnementales

-          l'autre face d'Haïti

-          Destination (Haïti, Guadeloupe, Martinique, Sainte-Lucie, Dominique)

-          Contact

**Comment by alberto56** [comment]
Il est maintenant possible d'ajouter des pages. J'ai ajouté "Nos actions". @samelohaiti tu peux ajouter les autres au https://www.toutnaturelcaraibes.org/admin/#/collections/pages

**Comment by samelohaiti** [comment]
Bonjour Albert,


J'espere que tu vas bien.



Voilà, on a terminé avec la mise en ligne des données. Certaines rubriques
comme *Personnalité du mois, Actualités, nos actions*… seront complétées au
fur et à mesure. Maintenant, j’aimerais que tu ajoutes les fiches sur le
site *https://www.toutnaturelcaraibes.org
<https://www.toutnaturelcaraibes.org>   *puis effacer le texte (lorem Lorem
ipsum…..) placé sous le nom de chaque site naturel (sur la photo) et *Popular
destination* et les autres boutons en anglais placé au bas de la page du
site. J’aimerais que tu arranges les rubriques afin qu’elles soient
visibles et détachées l’une de l’autre. En attendant les autres réseaux
sociaux, nous avons déjà un compte Facebook : *Tout Naturel Haïti-Caraïbes*,
tu pourrais l’associer au site. Sinon, tu peux me donner l’accès pour que
je puisse modifier certaines fonctionnalités, notamment la partie : *Ses
menaces par rapport aux changements climatiques et les mesures à prendre
pour s’adapter aux aléas naturels *dans les fiches. J’aimerais enlever
cette partie car ces fiches constituent une offre écotouristique. Donc, on
n’a pas besoin de mettre les informations non essentielles. Peux-tu me
donner ton avis là-dessus ? Ensuite, j’aimerais faire un mariage de
couleurs entre le fond du site et les rubriques. Je n’aime pas le noir et
blanc. Dis-moi ce que t’en penses ?

Pour l’ajout des rubriques en créole, je n’ai pas compris. Puisque j’ai
déjà des fiches en français, est-ce qu’il fallait en ajouter d’autres en
créole ?

Pour les fiches, tu peux les ajouter dans la rubrique *Destinations *à la
partie Haïti. J’attends pour Guadeloupe, Martinique, etc. Pour chaque
fiche, j’aimerais ajouter deux photos mais il me semble que c’est une seule
qui est visible sur le site.

NB. Une remarque importante : quand on a cliqué sur
*https://www.toutnaturelcaraibes.org
<https://www.toutnaturelcaraibes.org>, *je constate que c’est « *L’autre
face d’Haïti* » qui apparaît comme le titre du site web au lieu de « *Tout
Naturel  Haïti-Caraïbes* ». Cependant, l’autre face d’Haïti est une
rubrique du site.

Concernant l’application, on a terminé avec tous les contenus. Est-ce qu’on
ne pourrait pas appliquer la même formule qu’on a utilisée pour le site ?
Tu fais la base et mon équipe mettra les données. Dis-moi, est-ce que tu as
un modèle d’appli à nous proposer ? Sinon, je te partage « *Le guide
Guadeloupe *» (https://www.leguideguadeloupe.com) sur Play store. J’aime
cette présentation.

Voilà en grosso modo, les détails essentiels.


Bien a toi,

Messerne

Le ven. 12 févr. 2021 à 13:36, Albert Albala <notifications@github.com> a
écrit :
