### ISSUE TITLE
La partie "Description" n'est pas visible sur les fiches

### ISSUE THREAD

**Issue by alberto56** [maisonverte/maisonverte#20]
Exemple: Lac Azuei

**Comment by alberto56** [comment]
https://www.toutnaturelcaraibes.org/haiti/lac-azuei/

**Comment by samelohaiti** [comment]
![Capture Lac Azuei](https://user-images.githubusercontent.com/75354553/110681108-70632780-81a7-11eb-92fa-78ce72b8d0d1.png)

Dans cette capture du Lac Azuei, si tu regardes au bas de la photo, tu vois automatiquement le paragraphe "Sa biodiversite". Cependant, cette presentation doit commencer par "Description", le premier paragraphe de la presentation de toutes les fiches. Le texte est dans les les fiches mais il n'est pas visible sur le site.

**Comment by alberto56** [comment]
Je rouvre le ticket. Attentention de ne pas fermer ("close") les tickets qui ne sont pas compétés.

**Comment by samelohaiti** [comment]
Super. Peux-tu justifier les textes des fiches?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mer. 10 mars 2021 à 14:17, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
"Description" est maintenant visible, voir par exemple https://www.toutnaturelcaraibes.org/haiti/lac-azuei/
