### ISSUE TITLE
A la place de la rubrique « Destinations », je te suggère de rajouter les fiches, cette fois-ci, dans celle de : « Sites naturels et espaces de biodiversité ».

### ISSUE THREAD

**Issue by samelohaiti** [maisonverte/maisonverte#28]
Comme tu pouvais le constater, j’ai changé le nom de certaines rubriques comme :
-	« Destinations » qui deviennent « Sites naturels et espaces de biodiversité »
-	« Personnalité du mois » qui devient « Tribune des scientifiques »
-	« Actualités » qui deviennent « Actus écolos »
Puis j’ajoute une nouvelle rubrique : « Références bibliographiques »
NB. A la place de la rubrique « Destinations », je te suggère d’ajouter les fiches, cette fois-ci, dans celle de : « Sites naturels et espaces de biodiversité ».
En ce qui a trait aux autres rubriques comme : « Références bibliographiques, Tribunes des scientifiques, Actus écolos et « Sites naturels et espaces de biodiversité», je te demande de me donner la possibilité d’ajouter, en temps réel, des articles, documents pdf et images (inclus partage Facebook) parce que ces rubriques seront mises à jour de manière périodique.

**Comment by alberto56** [comment]
Cette tâche est trop vague, SVP ouvrir une seule tâche pour chacune des rubriques qu'on aimerait modifier: Exemple:

* Articles dans la section "actus écolos"
* Références bibliographiques contenant des PDF ou des liens
* Fiches de scientifiques dans "Tribunes des scientifiques"
* ...
