### ISSUE TITLE
Changer le titre "Destinations populaires"

### ISSUE THREAD

**Issue by samelohaiti** [maisonverte/maisonverte#30]
Dans cette partie situee au bas de page du site,
tu peux changer le titre "Destinations populaires" en "Sites naturels et espaces de biodiversite"

**Comment by samelohaiti** [comment]
![Capture d’écran 2021-04-04 112602](https://user-images.githubusercontent.com/75354553/113514383-28cc8300-953c-11eb-993a-a20c35d2302d.png)

**Comment by alberto56** [comment]
J'ai fait le changement mais c'est ce genre de changement que ton équipe pourrait faire assez facilement.

Voici ce dont à l'air le changement que j'ai fait:

https://github.com/maisonverte/maisonverte/commit/de09f799853cb9113f48b5bacb418b981b214b1d

Le code se trouve dans https://github.com/maisonverte/maisonverte/blob/master/docs/index.html
