### ISSUE TITLE
Ajouter les fiches sur leur propre page

### ISSUE THREAD

**Issue by alberto56** [maisonverte/maisonverte#9]
Alors, je veux parler des données (images et textes) concernant les sites naturels que j'ai mises dans fiches. Quand on va sur le site www.toutnaturelcaraibes.org, on voit ne que les photos. En cliquand sur '"Explorer Now"', le texte de la présentation du site naturel en question n'apparait pas.> Maintenant, j’aimerais que tu ajoutes les fiches sur le
site *https://www.toutnaturelcaraibes.org
<https://www.toutnaturelcaraibes.org> 

@samelohaiti SVP préciser ce que tu veux dire par là

**Comment by samelohaiti** [comment]
Alors, je veux parler des données (images et textes) concernant les sites
naturels que j'ai mises dans fiches. Quand on va sur le site
www.toutnaturelcaraibes.org, on ne voit que les photos. En cliquant sur
'"Explorer Now"', le texte de la présentation du site naturel en question
n'apparaît pas.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le jeu. 4 mars 2021 à 5:15 PM, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
Les fiches appraissent maintenant sur leur propre page, par exemple:

http://www.toutnaturelcaraibes.org/haiti/etang-miragoane/
